/**
 * M12/A2 — Thai audio batch pipeline (paid-gated).
 *
 * Reads the typed Thai seed (seed/thai/items.ts), builds the full clip
 * manifest — consonant letter names, vowel sounds (carrier-อ demonstration
 * form), tone-ear minimal-pair words, drillable word-bank syllables,
 * silent-leader words (unit 12, M14/A6), and spoken numeral names (unit 13,
 * M14/A6 — the digit NAME, not the glyph) — synthesizes each with Google
 * Chirp3-HD voice th-TH-Chirp3-HD-Achernar (the bake-off winner, owner
 * sign-off 2026-07-03), uploads to Vercel Blob under audio/thai/, and writes
 * the resulting URL back into thai_items.audioUrl.
 *
 * Blob paths are keyed by a hash of (provider, model, voice, language, text)
 * — NOT text alone — so a future voice change can never silently reuse a
 * stale clip generated by a different voice (the Mandarin pipeline's
 * scripts/generate-audio.ts:33-36 hashes text alone; this is the M12 fix,
 * scoped to the new audio/thai/ prefix only — existing Mandarin audio/ blob
 * paths and URLs are untouched).
 *
 * Idempotent + resumable like the Mandarin pipeline: existing blobs are
 * listed once and reused, never re-generated or overwritten.
 *
 * PAID GATE: pass --dry (or set DRY_RUN=1) to build the manifest and print
 * the clip count / total chars / estimated cost WITHOUT calling the Google
 * API, uploading to Blob, or touching the DB. The real run only happens
 * after the owner approves the dry-run's cost estimate.
 */
import { config } from "dotenv";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";

config({ path: ".env.local" });

const OUT_DIR = ".artifacts/thai-audio";
const MANIFEST_PATH = `${OUT_DIR}/manifest.json`;
const LEDGER_PATH = `${OUT_DIR}/ledger.json`;

const PROVIDER = "google";
const MODEL = "chirp3-hd";
const VOICE = "th-TH-Chirp3-HD-Achernar";
const LANGUAGE_CODE = "th-TH";
const COST_PER_MILLION_CHARS_USD = 30;

const DRY_RUN = process.argv.includes("--dry") || process.env.DRY_RUN === "1";

interface ClipSpec {
  itemId: string;
  text: string;
}

// Vowel forms are written with a placeholder circle (◌) marking where the
// consonant goes — not pronounceable on their own. The research doc itself
// demonstrates vowel sounds by attaching them to the mid-class carrier อ
// (e.g. the tone-diacritic table's "Example on a" column, and the unit-9
// carrier-อ family) — this reuses that exact methodology so every vowel gets
// a real, sayable Thai string rather than the literal placeholder glyph.
// The two "hidden vowel" rows (unwritten, described only in English prose)
// have no ◌ at all and are intentionally skipped — there is no written form
// to attach a carrier to.
function deriveVowelAudioText(display: string): string | null {
  if (!display.includes("◌")) return null;
  const firstForm = display.split(" / ")[0];
  return firstForm.replaceAll("◌", "อ");
}

async function buildManifest(): Promise<ClipSpec[]> {
  const { ALL_THAI_ITEMS } = await import("../seed/thai/items");
  const clips: ClipSpec[] = [];
  for (const item of ALL_THAI_ITEMS) {
    let text: string | null = null;
    if (item.kind === "consonant" && item.drillable) {
      // The acrophonic name (e.g. "ก ไก่") — used both as the unit 2-5 lesson
      // clip and as the audio-letter drill's prompt clip. `spokenName` (an
      // optional per-consonant override, e.g. ป → "ปอ ปลา") is preferred when
      // present so TTS says the letter's real name instead of the bare glyph,
      // which some consonants (e.g. the /bp/ plosive ป) render abruptly.
      text = item.metadata.spokenName ?? item.metadata.name;
    } else if (item.kind === "vowel") {
      text = deriveVowelAudioText(item.display);
    } else if (item.kind === "tone-word") {
      text = item.display;
    } else if (item.kind === "syllable" && item.drillable) {
      text = item.display;
    } else if (item.kind === "leader-word" && item.drillable) {
      // M14/A6: the leader word's own display (e.g. "หมา") — a real, sayable
      // word (the silent leader is part of its normal spelling/pronunciation,
      // nothing to strip).
      text = item.display;
    } else if (item.kind === "numeral" && item.drillable) {
      // M14/A6: the spoken digit NAME (e.g. "หนึ่ง" for ๑), NOT the bare
      // glyph — the glyph alone has no pronunciation of its own.
      text = item.metadata.name;
    }
    if (!text) continue;
    clips.push({ itemId: item.id, text });
  }
  return clips;
}

function pathFor(text: string): string {
  const hash = createHash("sha256")
    .update(`${PROVIDER}|${MODEL}|${VOICE}|${LANGUAGE_CODE}|${text}`)
    .digest("hex")
    .slice(0, 32);
  return `audio/thai/${hash}.mp3`;
}

async function synth(text: string, googleKey: string): Promise<Buffer> {
  const res = await fetch(
    `https://texttospeech.googleapis.com/v1/text:synthesize?key=${googleKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        input: { text },
        voice: { languageCode: LANGUAGE_CODE, name: VOICE },
        audioConfig: { audioEncoding: "MP3" },
      }),
    },
  );
  if (!res.ok) {
    throw new Error(`Google TTS failed for "${text}": ${res.status} ${(await res.text()).slice(0, 300)}`);
  }
  const { audioContent } = (await res.json()) as { audioContent: string };
  return Buffer.from(audioContent, "base64");
}

async function main() {
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

  const clips = await buildManifest();
  const totalChars = clips.reduce((sum, c) => sum + c.text.length, 0);
  const estCostUsd = (totalChars * COST_PER_MILLION_CHARS_USD) / 1e6;

  writeFileSync(MANIFEST_PATH, JSON.stringify(clips, null, 2), "utf8");

  console.log(
    `[manifest] ${clips.length} clips, ${totalChars} total chars, est cost $${estCostUsd.toFixed(4)} ` +
      `(Google Chirp3-HD $${COST_PER_MILLION_CHARS_USD}/1M chars).`,
  );
  console.log(`[manifest] written to ${MANIFEST_PATH}`);

  if (DRY_RUN) {
    console.log("[dry-run] no API calls made, no Blob uploads, no DB writes.");
    return;
  }

  const googleKey = (process.env.GOOGLE_TTS_API_KEY ?? "").trim().replace(/^["']|["']$/g, "");
  if (!googleKey) throw new Error("GOOGLE_TTS_API_KEY missing");

  const { put, list } = await import("@vercel/blob");
  const { neon } = await import("@neondatabase/serverless");
  const { drizzle } = await import("drizzle-orm/neon-http");
  const { eq } = await import("drizzle-orm");
  const schema = await import("../lib/db/schema");

  const sql = neon(process.env.DATABASE_URL!);
  const db = drizzle(sql, { schema });

  // Reuse any clips already in the store (idempotent re-runs, no overwrite).
  const existing = new Map<string, string>();
  let cursor: string | undefined;
  do {
    const res = await list({ prefix: "audio/thai/", cursor, limit: 1000 });
    for (const b of res.blobs) existing.set(b.pathname, b.url);
    cursor = res.cursor;
  } while (cursor);

  let made = 0;
  let reused = 0;
  const urlByItemId = new Map<string, string>();
  for (const clip of clips) {
    const pathname = pathFor(clip.text);
    let url = existing.get(pathname);
    if (!url) {
      process.stdout.write(`[tts] ${clip.itemId} ("${clip.text}") ... `);
      const buffer = await synth(clip.text, googleKey);
      const blob = await put(pathname, buffer, {
        access: "public",
        contentType: "audio/mpeg",
        addRandomSuffix: false,
      });
      url = blob.url;
      made++;
      console.log("uploaded");
    } else {
      reused++;
    }
    urlByItemId.set(clip.itemId, url);
  }

  for (const [itemId, url] of urlByItemId) {
    await db.update(schema.thaiItems).set({ audioUrl: url }).where(eq(schema.thaiItems.id, itemId));
  }

  let ledger: unknown[] = [];
  try {
    ledger = JSON.parse(readFileSync(LEDGER_PATH, "utf8"));
  } catch {
    // First run — no ledger yet.
  }
  ledger.push({
    ranAt: new Date().toISOString(),
    provider: PROVIDER,
    model: MODEL,
    voice: VOICE,
    clipCount: clips.length,
    totalChars,
    made,
    reused,
    estCostUsd,
  });
  writeFileSync(LEDGER_PATH, JSON.stringify(ledger, null, 2), "utf8");

  console.log(
    `\nDone. ${clips.length} clips (${made} generated, ${reused} reused). ` +
      `Audio URLs written to thai_items. Ledger: ${LEDGER_PATH}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
